// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzPIy7V8qBHWoWBOeyYnN41GJiwALsLPs',
    appId: '1:272886941202:web:9dc35b9f572b0861b47acb',
    messagingSenderId: '272886941202',
    projectId: 'user-try-15c04',
    authDomain: 'user-try-15c04.firebaseapp.com',
    storageBucket: 'user-try-15c04.firebasestorage.app',
    measurementId: 'G-26M89BFKXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWnFRQjfV-TaTvA1BYr5fMy2ucU4k9nk',
    appId: '1:272886941202:android:bfca5a029397c7b0b47acb',
    messagingSenderId: '272886941202',
    projectId: 'user-try-15c04',
    storageBucket: 'user-try-15c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcy8YhEEiTar28wqIEJnbcTR24-Gw_gY',
    appId: '1:272886941202:ios:2643910e780023adb47acb',
    messagingSenderId: '272886941202',
    projectId: 'user-try-15c04',
    storageBucket: 'user-try-15c04.firebasestorage.app',
    iosBundleId: 'com.example.blocApp',
  );
}
